### ISSUE TITLE
URI must be set (not null) before streaming.

### ISSUE THREAD

**Issue by tash649** [sonvister/Binance#100]
018-07-17 18:46:02.010 +00:00 [Information] JsonStreamController: Watchdog timer restarting stream controller (no data received in 60 minutes).  [thread: 32]
2018-07-17 18:46:02.037 +00:00 [Debug] RetryTaskController.ActionAsync: Task beginning...  [thread: 32]
2018-07-17 18:46:02.043 +00:00 [Debug] BinanceWebSocketStream.StreamAsync: Streaming initiated.  [thread: 32]
2018-07-17 18:46:02.526 +00:00 [Warning] BinanceWebSocketStream.StreamAsync: Unhandled exception.  [thread: 32]
System.InvalidOperationException: WebSocketStream: URI must be set (not null) before streaming.
   at Binance.WebSocket.WebSocketStream.<StreamActionAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Stream.BufferedJsonStream`1.<StreamAsync>d__9.MoveNext()
2018-07-17 18:46:02.633 +00:00 [Debug] BinanceWebSocketStream.StreamAsync: Streaming complete.  [thread: 32]
2018-07-17 18:46:02.717 +00:00 [Warning] RetryTaskController.ActionAsync: Unhandled action exception.  [thread: 32]
System.InvalidOperationException: WebSocketStream: URI must be set (not null) before streaming.
   at Binance.WebSocket.WebSocketStream.<StreamActionAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Stream.BufferedJsonStream`1.<StreamAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Utility.RetryTaskController.<ActionAsync>d__13.MoveNext()
2018-07-17 18:46:02.753 +00:00 [Debug] RetryTaskController.ActionAsync: Task pausing...  [thread: 32]
2018-07-17 18:46:02.800 +00:00 [Debug] BinanceHttpClient.RequestAsync: [GET] "/wapi/v3/systemStatus.html"
2018-07-17 18:46:03.244 +00:00 [Debug] BinanceWebSocketStreamController: System status (Normal).  [thread: 32]
2018-07-17 18:46:03.291 +00:00 [Debug] RetryTaskController: Delaying for 5000 msec.  [thread: 32]
2018-07-17 18:46:08.357 +00:00 [Debug] RetryTaskController.ActionAsync: Task resuming...  [thread: 37]
2018-07-17 18:46:08.380 +00:00 [Debug] BinanceWebSocketStream.StreamAsync: Streaming initiated.  [thread: 37]
2018-07-17 18:46:08.592 +00:00 [Warning] BinanceWebSocketStream.StreamAsync: Unhandled exception.  [thread: 37]
System.InvalidOperationException: WebSocketStream: URI must be set (not null) before streaming

**Comment by tash649** [comment]
0.2.0-beta5

**Comment by tash649** [comment]
UTC time

**Comment by tash649** [comment]
very similar with google issue (by time)

https://status.cloud.google.com/incident/cloud-networking/18012

and discord

https://status.discordapp.com/incidents/624vf01bm5yv
