### ISSUE TITLE
-1100: Illegal characters found in parameter 'quantity

### ISSUE THREAD

**Issue by spbsmile** [sonvister/Binance#17]
i want place order with `Quantity = 0.002m`

`await _binanceClient.Api.PlaceAsync(new LimitOrder(_binanceClient.User)
                {
                    Symbol = Symbol.BTC_USDT,
                    Side = Binance.Account.Orders.OrderSide.Buy,
                    Quantity = 0.002m,
                    Price = 16000
                });
`
i get exception: 
-		$exception	{Binance.Api.BinanceHttpException: [BadRequest]: 'Bad Request' - Illegal characters found in parameter 'quantity'; legal range is '^([0-9]{1,20})(\.[0-9]{1,20})?$'. (-1100)
   at Binance.Api.Json.BinanceJsonApi.<RequestAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Api.Json.BinanceJsonApi.<PlaceOrderAsync>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Binance.Api.BinanceApi.<PlaceAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at MusicWeb.Core.Orders.OrderAction.<BuyBinance>d__7.MoveNext() in C:\MusicWeb\MusicWeb\Core\Orders\OrderAction.cs:line 59}	Binance.Api.BinanceHttpException

why i get this error ?
this is restrict binance server api  ?

**Comment by spbsmile** [comment]
[biinance-official-api-error](https://github.com/binance-exchange/binance-official-api-docs/blob/master/errors.md#-1100-illegal_chars)

-1100 ILLEGAL_CHARS
Illegal characters found in a parameter.
Illegal characters found in parameter '%s'; legal range is '%s'.

**Comment by spbsmile** [comment]
upgrade  to latest alfa version close this problem

**Comment by sonvister** [comment]
@spbsmile, I'll assume this is the same as issue #8.
