### ISSUE TITLE
0.2.0-alpha35: web socket exceptions

### ISSUE THREAD

**Issue by rakewell** [sonvister/Binance#69]
I've been testing two versions simultaneously alpha30 and alpha35 and whilst I got no disconnections on alpha 30 during a 8 hour test period, I got several disconnections on alpha35. Here are the logs during that period for alpha35.

AggregateTradeSocket:
```

[info] 26/02/2018 9:18:12 AM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"
[fail] 26/02/2018 11:09:19 AM +11:00
       BinanceWebSocketStream.StreamAsync: Failed.  [thread: 75]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[info] 26/02/2018 11:09:23 AM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"
[fail] 26/02/2018 1:37:22 PM +11:00
       BinanceWebSocketStream.StreamAsync: Failed.  [thread: 47]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[info] 26/02/2018 1:37:25 PM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"

```
UserDataSocket:
```

[fail] 26/02/2018 3:16:31 PM +11:00
       DefaultWebSocketClient.StreamAsync: WebSocket receive exception.
      (exception: An internal WebSocket error occurred. Please see the innerException, if present, for more details. )

[fail] 26/02/2018 3:16:31 PM +11:00
       BinanceWebSocketStream.StreamAsync: Failed.  [thread: 67]
      (exception: An internal WebSocket error occurred. Please see the innerException, if present, for more details. )

```
```

2018-02-26 15:16:31,367 FATAL 1 ActivityLog - User Socket Unexpected exception occured of type WebSocketException. Message: An internal WebSocket error occurred. Please see the innerException, if present, for more details. 
..........Inner Exception..........
Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
..........Inner Exception..........
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.BinanceWebSocketStream.<StreamAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Stream.BufferedJsonStream`1.<StreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Utility.RetryTaskController.<<Begin>b__5_0>d.MoveNext()
. Source: System. Stack:    at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.BinanceWebSocketStream.<StreamAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Stream.BufferedJsonStream`1.<StreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Utility.RetryTaskController.<<Begin>b__5_0>d.MoveNext()
2018-02-26 15:16:31,368 INFO 1 ActivityLog - User Socket Unexpected exception occured of type WebSocketException. Message: An internal WebSocket error occurred. Please see the innerException, if present, for more details. 
..........Inner Exception..........
Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.IO.Stream.<>c.<BeginEndReadAsync>b__43_1(Stream stream, IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncTrimPromise`1.Complete(TInstance thisRef, Func`3 endMethod, IAsyncResult asyncResult, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketConnectionStream.<ReadAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Net.WebSockets.WebSocketBase.WebSocketOperation.<Process>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
..........Inner Exception..........
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.BinanceWebSocketStream.<StreamAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Stream.BufferedJsonStream`1.<StreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Utility.RetryTaskController.<<Begin>b__5_0>d.MoveNext()
. Source: System. Stack:    at System.Net.WebSockets.WebSocketBase.ThrowIfConvertibleException(String methodName, Exception exception, CancellationToken cancellationToken, Boolean aborted)
   at System.Net.WebSockets.WebSocketBase.<ReceiveAsyncCore>d__45.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Binance.WebSocket.DefaultWebSocketClient.<StreamAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.WebSocket.BinanceWebSocketStream.<StreamAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Stream.BufferedJsonStream`1.<StreamAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Binance.Utility.RetryTaskController.<<Begin>b__5_0>d.MoveNext()



```

**Comment by rakewell** [comment]
further testing with version **0.2.0-alpha37**:

User Socket:
```

[fail] 27/02/2018 12:04:27 AM +11:00
       UserDataWebSocketStreamControl.HandleTimer: Failed to ping user data stream (1st attempt).
      (exception: [BadRequest]: 'Bad Request' - This listenKey does not exist. (-1125))
[dbug] 27/02/2018 12:04:27 AM +11:00
       UserDataWebSocketStreamControl.HandleTimer: Keep-alive user stream ("q8tlzr9F4NAeiTRbM8LTkzyvSIMwB19V4VIJMwKejxJPPRa2r76bl4tJDyKy").  [thread: 83]
[fail] 27/02/2018 12:04:30 AM +11:00
       UserDataWebSocketStreamControl.HandleTimer: Failed to ping user data stream (2nd attempt).
      (exception: [BadRequest]: 'Bad Request' - This listenKey does not exist. (-1125))
[dbug] 27/02/2018 12:04:30 AM +11:00
```

Aggregate Trade:
```

[info] 26/02/2018 5:34:25 PM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"
[fail] 27/02/2018 1:35:16 AM +11:00
       BinanceWebSocketStream.StreamAsync: Fail.  [thread: 82]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[info] 27/02/2018 1:35:18 AM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"
[fail] 27/02/2018 4:59:00 AM +11:00
       BinanceWebSocketStream.StreamAsync: Fail.  [thread: 27]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[info] 27/02/2018 4:59:03 AM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"
[fail] 27/02/2018 7:25:16 AM +11:00
       BinanceWebSocketStream.StreamAsync: Fail.  [thread: 41]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[info] 27/02/2018 7:25:19 AM +11:00
       BinanceWebSocketStream.StreamAsync: "wss://stream.binance.com:9443/stream?streams=lrcbtc@aggTrade/arnbtc@aggTrade/nanobtc@aggTrade/etcbtc@aggTrade/ltcbtc@aggTrade/dgdbtc@aggTrade/btcusdt@aggTrade"

```

These errors did not appear with testing alpha30 during the same period.

**Comment by rakewell** [comment]
further testing with version 0.2.0-alpha39:

Aggregate Trade:

No disconnections in 12 hour period:

User Socket:
```

[warn] 1/03/2018 10:04:31 PM +11:00
       DefaultWebSocketClient.StreamAsync: WebSocket receive exception (state: Aborted).
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[dbug] 1/03/2018 10:04:31 PM +11:00
       DefaultWebSocketClient.StreamAsync: Task complete.  [thread: 60]
[info] 1/03/2018 10:04:31 PM +11:00
       BinanceWebSocketStream.StreamActionAsync: End streaming...
       (wss://stream.binance.com:9443/ws/mXDH8FcrSAYYiDXXcVix0zElTQEx2MdMAtC2nRfi7eirnZoVTYVgzD7ukQ4b)
[dbug] 1/03/2018 10:04:31 PM +11:00
       UserDataClient.Unsubscribe: "mXDH8FcrSAYYiDXXcVix0zElTQEx2MdMAtC2nRfi7eirnZoVTYVgzD7ukQ4b" (callback: no).  [thread: 63]
[warn] 1/03/2018 10:04:31 PM +11:00
       BinanceWebSocketStream.StreamAsync: Unhandled exception.  [thread: 60]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)
[dbug] 1/03/2018 10:04:31 PM +11:00
       BinanceWebSocketStream.StreamAsync: Streaming complete.  [thread: 60]
[warn] 1/03/2018 10:04:31 PM +11:00
       RetryTaskController: Unhandled action exception.  [thread: 60]
      (exception: The remote party closed the WebSocket connection without completing the close handshake.)

[warn] 2/03/2018 5:54:59 AM +11:00
       DefaultWebSocketClient.StreamAsync: WebSocket receive exception (state: Aborted).
      (exception: An internal WebSocket error occurred. Please see the innerException, if present, for more details. )
[dbug] 2/03/2018 5:54:59 AM +11:00
       DefaultWebSocketClient.StreamAsync: Task complete.  [thread: 40]
[info] 2/03/2018 5:54:59 AM +11:00
       BinanceWebSocketStream.StreamActionAsync: End streaming...
       (wss://stream.binance.com:9443/ws/tjndyRDJnqTHfqOAT2wxckRJ4nMiJ6bhtYpBzuBaKfM8mrssJwACCQ9LzKd0)
[warn] 2/03/2018 5:54:59 AM +11:00
       BinanceWebSocketStream.StreamAsync: Unhandled exception.  [thread: 40]
      (exception: An internal WebSocket error occurred. Please see the innerException, if present, for more details. )
[dbug] 2/03/2018 5:54:59 AM +11:00
       BinanceWebSocketStream.StreamAsync: Streaming complete.  [thread: 40]
[warn] 2/03/2018 5:54:59 AM +11:00
       RetryTaskController: Unhandled action exception.  [thread: 40]
      (exception: An internal WebSocket error occurred. Please see the innerException, if present, for more details. )
[dbug] 2/03/2018 5:54:59 AM +11:00
       RetryTaskController: Task pausing...  [thread: 40]


```

**Comment by sonvister** [comment]
@rakewell, you may wish to use the updated version of the `FileLogger` that prints all inner exceptions.

**Comment by rakewell** [comment]
thanks @sonvister, I have done so and will test using the latest version (alpha41) and report any issues if necessary
