### ISSUE TITLE
TRXBTC symbol for 1M has negative volume

### ISSUE THREAD

**Issue by sguryev** [sonvister/Binance#83]
https://github.com/sonvister/Binance/blob/da2967a181212fda937a28ed6fcdd284f0778966/src/Binance/Market/Candlestick.cs#L134
**Reprosteps**: `await _binanceApi.GetCandlesticksAsync("TRXBTC", CandlestickInterval.Month);`
**Json**:
![image](https://user-images.githubusercontent.com/6978458/38212062-22f308a6-36c5-11e8-8b4a-f8cc6136ded2.png)

**Inner exception**: `Candlestick: volume must not be less than 0. Parameter name: volume`

**StackTrace**:    at Binance.Candlestick..ctor(String symbol, CandlestickInterval interval, DateTime openTime, Decimal open, Decimal high, Decimal low, Decimal close, Decimal volume, DateTime closeTime, Decimal quoteAssetVolume, Int64 numberOfTrades, Decimal takerBuyBaseAssetVolume, Decimal takerBuyQuoteAssetVolume)
   at Binance.Serialization.CandlestickSerializer.<>c__DisplayClass14_0.<DeserializeMany>b__0(JToken item)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Binance.BinanceApi.<GetCandlesticksAsync>d__26.MoveNext()

**Comment by sonvister** [comment]
@sguryev, thanks for reporting the exception. I have asked if the data is valid on the official API Telegram. Although, I can't imagine what a negative volume would represent if it is valid data.

**Comment by sguryev** [comment]
@sonvister absolutely agree with you. I'm getting a bunch of symbols for 1M using `Task.WhenAll()` and now have to make a tricky `Task.Run()` workaround in order to swallow the exception. We can point them to the specific API call and ask about this negative value though

**Comment by sonvister** [comment]
UPDATE: The query (https://api.binance.com/api/v1/klines?symbol=TRXBTC&interval=1M) still returns a negative volume....
